import sdl2

AUDIODEVICEADDED = sdl2.SDL_AUDIODEVICEADDED
AUDIODEVICEREMOVED = sdl2.SDL_AUDIODEVICEREMOVED

CONTROLLERAXISMOTION = sdl2.SDL_CONTROLLERAXISMOTION
CONTROLLERBUTTONDOWN = sdl2.SDL_CONTROLLERBUTTONDOWN
CONTROLLERBUTTONUP = sdl2.SDL_CONTROLLERBUTTONUP

CONTROLLERDEVICEADDED = sdl2.SDL_CONTROLLERDEVICEADDED
CONTROLLERDEVICEREMOVED = sdl2.SDL_CONTROLLERDEVICEREMOVED
CONTROLLERDEVICEREMAPPED = sdl2.SDL_CONTROLLERDEVICEREMAPPED

FINGERMOTION = sdl2.SDL_FINGERMOTION
FINGERDOWN = sdl2.SDL_FINGERDOWN
FINGERUP = sdl2.SDL_FINGERUP

KEYDOWN = sdl2.SDL_KEYDOWN
KEYUP = sdl2.SDL_KEYUP

JOYAXISMOTION = sdl2.SDL_JOYAXISMOTION
JOYBALLMOTION = sdl2.SDL_JOYBALLMOTION


JOYHATMOTION = sdl2.SDL_JOYHATMOTION

JOYBUTTONDOWN = sdl2.SDL_JOYBUTTONDOWN
JOYBUTTONUP = sdl2.SDL_JOYBUTTONUP

JOYDEVICEADDED = sdl2.SDL_JOYDEVICEADDED
JOYDEVICEREMOVED = sdl2.SDL_JOYDEVICEREMOVED

MOUSEMOTION = sdl2.SDL_MOUSEMOTION

MOUSEDOWN = sdl2.SDL_MOUSEBUTTONDOWN
MOUSEUP = sdl2.SDL_MOUSEBUTTONUP

MOUSEWHEEL = sdl2.SDL_MOUSEWHEEL

MULTIGESTURE = sdl2.SDL_MULTIGESTURE

QUIT = sdl2.SDL_QUIT

SYSWMEVENT = sdl2.SDL_SYSWMEVENT

TEXTEDITING = sdl2.SDL_TEXTEDITING

TEXTINPUT = sdl2.SDL_TEXTINPUT

USEREVENT = sdl2.SDL_USEREVENT

WINDOWEVENT = sdl2.SDL_WINDOWEVENT